# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
   from = "/api/hello-world"
   to = "/.netlify/functions/hello-world"
   status = 200
   force = true
  [[redirects]]
   from = "/api/pokedex"
   to = "/.netlify/functions/pokedex"
   status = 200
   force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Custom-Header = "foo"
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
